---
name: ansible-playbook
on: [deployment, push]

jobs:
  ansible-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade Ansible
        run: |
          pip install --upgrade ansible==2.9.9

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker run CentOS7 image sudo installed
        run: |
          docker run -d -t --name=mycontainer \
          tomonorimatsumura/ansible-test:latest

      - name: Install Ansible galaxy roles
        run: |
          ansible-galaxy install -r tests/roles/requirements.yml -p tests/roles

      - name: Execute ansible-playbook command
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          ansible-playbook -i 'mycontainer,' -c docker -u ansible tests/test.yml

      - name: Check idempotency
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          ansible-playbook -i 'mycontainer,' -c docker -u ansible tests/test.yml

      - name: Check if the command works
        run: |
          docker exec --tty mycontainer env TERM=xterm circleci version

      - name: Show Ansible version
        run: ansible --version

      - name: Show OS information
        run: |
          docker exec --tty mycontainer env TERM=xterm cat /etc/redhat-release
