---
name: build
on: [deployment, push]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ansible lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            tasks/main.yml
            molecule/default/converge.yml
            molecule/default/verify.yml
          args: "-x 106"

  ansible:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos7
          - centos8
        ansible-version:
          - ansible
          - ansible-base
        python-version:
          - 2.7
          - 3.6
          - 3.7
          - 3.8
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ansible
        run: |
          pip install ${{ matrix.ansible-version }}

      - name: Docker run CentOS image sudo installed
        run: |
          docker run -d -t --name=${{ matrix.distro }} \
          ghcr.io/docker-hub-tm/ansible-test/${{ matrix.distro }}:latest

      - name: Install Ansible galaxy roles
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          ansible-galaxy role install \
          -r requirements.yml

      - name: Install Ansible galaxy collections
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          ansible-galaxy collection install \
          -r requirements.yml

      - name: Execute ansible-playbook command
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          ansible-playbook -i ${{ matrix.distro }}, \
          -c docker -u ansible molecule/default/converge.yml

      - name: Check idempotency
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          ansible-playbook -i ${{ matrix.distro }}, \
          -c docker -u ansible molecule/default/converge.yml

      - name: Make sure the command works
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          ansible-playbook -i ${{ matrix.distro }}, \
          -c docker -u ansible molecule/default/verify.yml

  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos7
          - centos8
        python-version:
          - 3.6
          - 3.7
          - 3.8

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r molecule/requirements.txt

      - name: Test with molecule
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_NO_LOG: False
        run: |
          molecule test

  trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@56310d7

  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@665205c
        with:
          config_file: .yamllint
