---
name: build
on: [deployment, push]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install ansible-lint
        run: |
          pip install "ansible-lint[community,yamllint]"

      - name: Install galaxy roles
        run: |
          ansible-galaxy install git+https://github.com/${{ github.repository }},${{ github.sha }}

      - name: Execulte ansible-lint
        run: |
          ansible-lint

      - name: Show ansible-lint version
        run: |
          pip list | grep ansible \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
          ansible-lint --version

  molecule-centos7:
    uses: github-actions-reusable-workflows/molecule-docker/.github/workflows/workflows.yml@main
    with:
      molecule-image: ghcr.io/docker-hub-tm/ansible-test/centos7:latest

  molecule-centos8:
    uses: github-actions-reusable-workflows/molecule-docker/.github/workflows/workflows.yml@main
    with:
      molecule-image: ghcr.io/docker-hub-tm/ansible-test/centos8:latest

  trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@56310d70ae8fd21afec8d4307d2d9ab6c15e7c5d

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute yamllint
        run: yamllint *

      - name: Show yamllint version
        run: yamllint --version
