---
name: Build
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build CentOS7 image sudo installed
        run: docker build tests/. -t centos7sudo

      - name: Docker run CentOS7 image sudo installed
        run: docker run -d -t --name=mycontainer centos7sudo

      - name: Install Ansible galaxy roles
        run: ansible-galaxy install -r tests/roles/requirements.yml -p tests/roles

      - name: Execute ansible-playbook command
        run: ansible-playbook -i 'mycontainer,' -c docker tests/test.yml

      - name: Check idempotency
        run: ansible-playbook -i 'mycontainer,' -c docker tests/test.yml

      - name: Check if the command works
        run: |
          docker exec --tty mycontainer env TERM=xterm circleci version

      - name: Show Ansible version
        run: ansible --version

      - name: Show OS information
        run: docker exec --tty mycontainer env TERM=xterm cat /etc/redhat-release
