---
name: build
on: [deployment, push]

jobs:
  ansible-lint:
    uses: github-actions-reusable-workflows/ansible-lint/.github/workflows/workflows.yml@main

  trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@56310d70ae8fd21afec8d4307d2d9ab6c15e7c5d

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute yamllint
        run: yamllint *

      - name: Show yamllint version
        run: yamllint --version
